### ISSUE TITLE
About task embedding

### ISSUE THREAD

**Issue by zgzjdx** [tuvuumass/task-transferability#1]
Hi!
Thank you for open source your code for us to study.
I have the following questions:
    1.  I don't quite understand the meaning of the variables in formula(2) of your paper, which is the expected covariance of the gradients of the log-likelihood. Could you please explain it to me in more detail? i.e, what is the nabla_thelta?
    2.  In your code run_taskemb_SL.py or run_taskemb_CR.py, the fisher score was simply computed by model parameter's grad like score = score ** args.pow (which is 2.0 by default) is that right? Does this correspond to formula(2) in the paper? But I think score = score ** args.pow seems to be inconsistent with formula(2)

Looking forward to your reply, thanks!

**Comment by tuvuumass** [comment]
Hey @zgzjdx! Thanks for your interest! 
1. The ![equation](https://render.githubusercontent.com/render/math?math=\nabla) symbol denotes the gradient, and ![equation](https://render.githubusercontent.com/render/math?math=\nabla_{\theta}\log%20P_\theta(y|x)) is the gradient of the log likelihood at ![equation](https://render.githubusercontent.com/render/math?math=\theta). 
2. To reduce computational complexity, we only consider the diagonal entries of the Fisher information matrix, which corresponds to the square of the gradients.
